apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  octa_client_id: MG9hMjBiMnVrdklWR3EyY1Y1ZDc=
  pgpassword: SEBTaDFDb1IzIQ==
  pguser: aWxpeWFiMDlAcHMtZGItc3RhZ2U=
  # Example:
  # password: {{ .Values.password | b64enc }}